<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1FLO5NT" failures="2" tests="4" name="com.mk.tests.LoginTest" time="52.633" errors="0" timestamp="2025-01-20T18:56:48 IST" skipped="0">
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="20.754"/>
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="13.547">
    <failure message="
Expecting actual:
  &quot;https://www.saucedemo.com/&quot;
to contain:
  &quot;inventory&quot; " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
Expecting actual:
  "https://www.saucedemo.com/"
to contain:
  "inventory" 
at com.mk.tests.LoginTest.loginTest(LoginTest.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)
at org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="3.990">
    <failure message="
Expecting actual:
  &quot;https://www.saucedemo.com/&quot;
to contain:
  &quot;inventory&quot; " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
Expecting actual:
  "https://www.saucedemo.com/"
to contain:
  "inventory" 
at com.mk.tests.LoginTest.loginTest(LoginTest.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)
at org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="14.342"/>
</testsuite> <!-- com.mk.tests.LoginTest -->
