<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1FLO5NT" failures="1" tests="3" name="com.mk.tests.LoginTest" time="27.009" errors="0" timestamp="2025-01-20T11:20:46 IST" skipped="0">
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="4.853"/>
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="9.845">
    <failure message="
Expecting actual:
  &quot;https://www.saucedemo.com/&quot;
to contain:
  &quot;inventory&quot; " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
Expecting actual:
  "https://www.saucedemo.com/"
to contain:
  "inventory" 
at com.mk.tests.LoginTest.loginTest(LoginTest.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)
at org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="12.311"/>
</testsuite> <!-- com.mk.tests.LoginTest -->
